import {
  concept,
  conceptRelationship,
  knowledgeAsset,
  knowledgeCatalog,
  learningExperience,
  mathematicsDomain,
  topic,
} from "../domain/mathematical-knowledge.js";

/**
 * A deliberately small, published Functions graph. It proves stable identity,
 * typed relationships, version-aware knowledge resolution, representations,
 * misconception assets, bridges, and all three pedagogical layers. It is not a
 * curriculum-management system or a full mathematics catalogue.
 */
export const functionsSeedKnowledge = knowledgeCatalog({
  domains: [
    mathematicsDomain({
      id: "mathematics.school-foundations",
      title: "School Mathematics Foundations",
      description: "Seed mathematical scope for foundational function concepts.",
      version: "math-lumina.seed.v1",
    }),
  ],
  topics: [
    topic({
      id: "topic.functions",
      domainId: "mathematics.school-foundations",
      title: "Functions",
      description: "Seed topic for relationships between inputs, outputs, and functional rules.",
      version: "math-lumina.seed.v1",
    }),
  ],
  concepts: [
    concept({
      id: "concept.function",
      topicId: "topic.functions",
      title: "What is a Function?",
      conceptualDescription: "A function associates each permitted input with one output according to a rule.",
      version: "math-lumina.seed.v1",
    }),
    concept({
      id: "concept.domain-range",
      topicId: "topic.functions",
      title: "Domain and Range",
      conceptualDescription: "The domain describes permitted inputs and the range describes outputs produced by a function.",
      version: "math-lumina.seed.v1",
    }),
    concept({
      id: "concept.inverse-function",
      topicId: "topic.functions",
      title: "Inverse Functions",
      conceptualDescription: "An inverse function reverses an input-output relationship when an inverse exists.",
      version: "math-lumina.seed.v1",
    }),
  ],
  relationships: [
    conceptRelationship({
      id: "relationship.function-prerequisite-domain-range",
      kind: "prerequisite",
      sourceConceptId: "concept.function",
      targetConceptId: "concept.domain-range",
      rationale: "The input-output role of a function is useful context before exploring domain and range.",
      version: "math-lumina.seed.v1",
    }),
    conceptRelationship({
      id: "relationship.function-related-domain-range",
      kind: "related",
      sourceConceptId: "concept.function",
      targetConceptId: "concept.domain-range",
      rationale: "Domain and range describe the inputs and outputs of a function relationship.",
      version: "math-lumina.seed.v1",
    }),
    conceptRelationship({
      id: "relationship.function-bridge-inverse-function",
      kind: "concept-bridge",
      sourceConceptId: "concept.function",
      targetConceptId: "concept.inverse-function",
      rationale: "An input-output relationship can later be connected to reversing a relationship.",
      version: "math-lumina.seed.v1",
    }),
    conceptRelationship({
      id: "relationship.domain-range-prerequisite-inverse-function",
      kind: "prerequisite",
      sourceConceptId: "concept.domain-range",
      targetConceptId: "concept.inverse-function",
      rationale: "Whether a reversed rule gives each input one output is a question about domain and range.",
      version: "math-lumina.seed.v1",
    }),
  ],
  assets: [
    knowledgeAsset({
      id: "asset.function.vending-machine-representation",
      kind: "representation",
      representationForm: "contextual",
      title: "Function as a vending machine",
      content: "An input selection goes into a vending machine and one output item comes out according to the machine's rule.",
      conceptIds: ["concept.function"],
      supportedLayers: ["intuition"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.function.mapping-representation",
      kind: "representation",
      representationForm: "visual",
      title: "Input-output mapping arrows",
      content: "A mapping representation can show each input arrow pointing to one output, without requiring a visual component.",
      conceptIds: ["concept.function"],
      supportedLayers: ["intuition", "mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.function.rule-representation",
      kind: "representation",
      representationForm: "symbolic",
      title: "Function rule notation",
      content: "The symbolic representation f(x) = 2x describes an output rule for each input x.",
      conceptIds: ["concept.function"],
      supportedLayers: ["mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.function.table-representation",
      kind: "representation",
      representationForm: "numerical",
      title: "Input-output value table",
      content: "A numerical table can pair inputs 1, 2, 3 with outputs 2, 4, 6 for the rule f(x) = 2x.",
      conceptIds: ["concept.function"],
      supportedLayers: ["intuition", "mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.function.graph-representation",
      kind: "representation",
      representationForm: "graphical",
      title: "Graphical function representation",
      content: "A graph can represent how x-values and y-values are paired for a rule, independently of any chart component.",
      conceptIds: ["concept.function"],
      supportedLayers: ["mechanics", "exam-patterns"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.function.input-output-example",
      kind: "example",
      title: "A rule that doubles an input",
      content: "For the rule f(x) = 2x, input 3 produces output 6.",
      conceptIds: ["concept.function"],
      supportedLayers: ["intuition", "mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.function.one-input-two-outputs-non-example",
      kind: "non-example",
      title: "One input with two outputs",
      content: "A relation that gives the same input two different outputs does not meet the defining function condition.",
      conceptIds: ["concept.function"],
      supportedLayers: ["intuition", "mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.function.notation-procedure",
      kind: "procedure",
      title: "Reading function notation",
      content: "Read f(x) = 2x + 3 as: take x, multiply by 2, then add 3.",
      conceptIds: ["concept.function"],
      supportedLayers: ["mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.function.input-output-misconception",
      kind: "misconception",
      title: "Function rule versus one-to-one rule",
      content: "Different inputs may share an output; the defining condition concerns each input having one output.",
      conceptIds: ["concept.function"],
      supportedLayers: ["intuition", "mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.function.temperature-application",
      kind: "application",
      title: "Temperature conversion",
      content: "A conversion rule can associate a temperature in one unit with a temperature in another unit.",
      conceptIds: ["concept.function"],
      supportedLayers: ["intuition"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.function.identifying-function-exam-pattern",
      kind: "exam-pattern",
      title: "Recognising a function-definition question",
      content: "When deciding whether a relation is a function, examine whether any input is paired with more than one output.",
      conceptIds: ["concept.function"],
      supportedLayers: ["exam-patterns"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.function.domain-range-exam-pattern",
      kind: "exam-pattern",
      title: "Recognising a domain-and-range question",
      content: "When asked for domain and range, identify permitted inputs separately from outputs produced by the relation.",
      conceptIds: ["concept.domain-range"],
      supportedLayers: ["exam-patterns"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.inverse-function.reverse-mapping-representation",
      kind: "representation",
      representationForm: "visual",
      title: "Reversing an input-output mapping",
      content: "A reverse mapping can invite reflection on what changes when inputs and outputs exchange roles, without deciding whether an inverse exists.",
      conceptIds: ["concept.inverse-function"],
      supportedLayers: ["intuition"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.domain-range.accepted-input-representation",
      kind: "representation",
      representationForm: "contextual",
      title: "A rule that only accepts certain inputs",
      content: "A lift serves floors 1 to 10, so a request for floor 12 is not something it can accept. The floors it accepts correspond to a domain, and the floors it can reach correspond to a range.",
      conceptIds: ["concept.domain-range"],
      supportedLayers: ["intuition"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.domain-range.mapping-representation",
      kind: "representation",
      representationForm: "visual",
      title: "Domain and range on a mapping",
      content: "On a mapping from inputs to outputs, the domain is the collection of values on the input side and the range is the collection of values actually reached on the output side.",
      conceptIds: ["concept.domain-range"],
      supportedLayers: ["intuition", "mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.domain-range.interval-representation",
      kind: "representation",
      representationForm: "symbolic",
      title: "Writing a domain in symbols",
      content: "The domain of f(x) = 1 / (x - 2) can be written as x in R, x not equal to 2, because the rule produces no output when x is 2.",
      conceptIds: ["concept.domain-range"],
      supportedLayers: ["mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.domain-range.table-representation",
      kind: "representation",
      representationForm: "numerical",
      title: "Domain and range from a table of values",
      content: "For inputs 1, 2, 3 paired with outputs 2, 4, 6, the domain is 1, 2, 3 and the range is 2, 4, 6.",
      conceptIds: ["concept.domain-range"],
      supportedLayers: ["intuition", "mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.domain-range.graph-representation",
      kind: "representation",
      representationForm: "graphical",
      title: "Domain and range read from a graph",
      content: "Reading a graph across describes the domain and reading it upward describes the range, independently of any chart component.",
      conceptIds: ["concept.domain-range"],
      supportedLayers: ["mechanics", "exam-patterns"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.domain-range.square-root-example",
      kind: "example",
      title: "A rule that restricts its own inputs",
      content: "For f(x) = sqrt(x), an input below 0 produces no real output, so the domain is x greater than or equal to 0 and the range is f(x) greater than or equal to 0.",
      conceptIds: ["concept.domain-range"],
      supportedLayers: ["mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.domain-range.division-non-example",
      kind: "non-example",
      title: "An input the rule cannot accept",
      content: "For f(x) = 1 / x, the input 0 is not in the domain, because no output is defined when the divisor is 0.",
      conceptIds: ["concept.domain-range"],
      supportedLayers: ["mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.domain-range.stating-domain-procedure",
      kind: "procedure",
      title: "Stating a domain from a rule",
      content: "Identify the inputs the rule cannot process, such as a divisor of 0 or a square root of a negative number, and exclude those from the permitted inputs.",
      conceptIds: ["concept.domain-range"],
      supportedLayers: ["mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.domain-range.range-misconception",
      kind: "misconception",
      title: "Range versus every value an output might take",
      content: "The range is the set of outputs the rule actually produces, not every value an output could be. For f(x) = x squared, the range is f(x) greater than or equal to 0, not all real numbers.",
      conceptIds: ["concept.domain-range"],
      supportedLayers: ["mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.domain-range.ticket-application",
      kind: "application",
      title: "A price that applies only to whole tickets",
      content: "A ticket price rule applies to whole numbers of tickets, so its permitted inputs are whole numbers even though its outputs are amounts of money.",
      conceptIds: ["concept.domain-range"],
      supportedLayers: ["intuition"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.inverse-function.undo-representation",
      kind: "representation",
      representationForm: "contextual",
      title: "An inverse as an undoing",
      content: "Putting shoes on and taking them off are opposite actions: doing one and then the other returns the starting situation. An inverse relates to a rule in the same way.",
      conceptIds: ["concept.inverse-function"],
      supportedLayers: ["intuition"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.inverse-function.notation-representation",
      kind: "representation",
      representationForm: "symbolic",
      title: "Inverse function notation",
      content: "The inverse of f is written f^-1. If f(x) = 2x then f^-1(x) = x / 2, because halving returns the input that doubling started from.",
      conceptIds: ["concept.inverse-function"],
      supportedLayers: ["mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.inverse-function.table-representation",
      kind: "representation",
      representationForm: "numerical",
      title: "An inverse read from a table",
      content: "If a rule pairs inputs 1, 2, 3 with outputs 2, 4, 6, its inverse pairs inputs 2, 4, 6 with outputs 1, 2, 3.",
      conceptIds: ["concept.inverse-function"],
      supportedLayers: ["intuition", "mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.inverse-function.reflection-line-representation",
      kind: "representation",
      representationForm: "graphical",
      title: "The graph of an inverse",
      content: "The graph of f^-1 is the graph of f reflected in the line y = x, independently of any chart component.",
      conceptIds: ["concept.inverse-function"],
      supportedLayers: ["mechanics", "exam-patterns"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.inverse-function.doubling-halving-example",
      kind: "example",
      title: "Doubling and halving",
      content: "For f(x) = 2x, the input 5 gives the output 10, and the inverse takes 10 back to 5.",
      conceptIds: ["concept.inverse-function"],
      supportedLayers: ["intuition", "mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.inverse-function.squaring-non-example",
      kind: "non-example",
      title: "A rule with no inverse function",
      content: "For f(x) = x squared over all real inputs, both -3 and 3 produce 9, so reversing 9 does not identify a single input and no inverse function exists unless the domain is restricted.",
      conceptIds: ["concept.inverse-function"],
      supportedLayers: ["mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.inverse-function.finding-inverse-procedure",
      kind: "procedure",
      title: "Finding an inverse from a rule",
      content: "Write the rule as y in terms of x, exchange x and y, then solve for y.",
      conceptIds: ["concept.inverse-function"],
      supportedLayers: ["mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.inverse-function.reciprocal-misconception",
      kind: "misconception",
      title: "Inverse notation versus a reciprocal",
      content: "f^-1(x) denotes the inverse of f, not 1 divided by f(x). For f(x) = 2x the inverse is x / 2, while the reciprocal is 1 / (2x).",
      conceptIds: ["concept.inverse-function"],
      supportedLayers: ["mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.inverse-function.currency-application",
      kind: "application",
      title: "Converting an amount back again",
      content: "A rule converting an amount from one currency to another has a reverse rule converting it back, when each amount corresponds to exactly one converted amount.",
      conceptIds: ["concept.inverse-function"],
      supportedLayers: ["intuition"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.inverse-function.exam-pattern",
      kind: "exam-pattern",
      title: "Recognising an inverse-function question",
      content: "When asked for an inverse, first check whether each output comes from exactly one input, then exchange the roles of input and output.",
      conceptIds: ["concept.inverse-function"],
      supportedLayers: ["exam-patterns"],
      version: "math-lumina.seed.v1",
    }),
  ],
  experiences: [
    learningExperience({
      id: "experience.function.intuition-vending-machine",
      title: "Function intuition through an input-output machine",
      intent: "intuition",
      targetConceptIds: ["concept.function"],
      knowledgeAssetIds: [
        "asset.function.vending-machine-representation",
        "asset.function.mapping-representation",
        "asset.function.table-representation",
        "asset.function.input-output-example",
        "asset.function.temperature-application",
      ],
      pedagogicalLayers: ["intuition"],
      deliveryRequirements: ["displayed-text"],
      learnerInteractionRequirements: ["reflection"],
      expectedEvidenceTypes: ["reflection"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.function.low-energy-core-insight",
      title: "Function core insight",
      intent: "low-energy",
      targetConceptIds: ["concept.function"],
      knowledgeAssetIds: ["asset.function.vending-machine-representation"],
      pedagogicalLayers: ["intuition"],
      deliveryRequirements: ["displayed-text"],
      learnerInteractionRequirements: [],
      expectedEvidenceTypes: [],
      completionSemantics: { requiresLearnerInteraction: false, evidenceRequiredForCompletion: false },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.function.practice-input-output",
      title: "Practise tracing an input-output rule",
      intent: "practice",
      targetConceptIds: ["concept.function"],
      knowledgeAssetIds: ["asset.function.input-output-example"],
      // `practice` is suitable at `mechanics` and `exam-patterns`, never at
      // `intuition`. Declared at `intuition`, this experience was filtered out
      // of every decision and no learner was ever offered a question to try.
      pedagogicalLayers: ["mechanics"],
      deliveryRequirements: ["displayed-text", "typed-input"],
      learnerInteractionRequirements: ["practice-input"],
      expectedEvidenceTypes: ["practice-attempt"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.function.mechanics-notation",
      title: "Function notation and mechanics",
      intent: "mechanics",
      targetConceptIds: ["concept.function"],
      knowledgeAssetIds: [
        "asset.function.rule-representation",
        "asset.function.input-output-example",
        "asset.function.notation-procedure",
        "asset.function.one-input-two-outputs-non-example",
        "asset.function.input-output-misconception",
      ],
      pedagogicalLayers: ["mechanics"],
      deliveryRequirements: ["displayed-text", "displayed-notation"],
      learnerInteractionRequirements: ["reflection"],
      expectedEvidenceTypes: ["reflection"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.function.exam-patterns-identifying-function",
      title: "Exam pattern: identify a function relation",
      intent: "exam-patterns",
      targetConceptIds: ["concept.function"],
      knowledgeAssetIds: [
        "asset.function.identifying-function-exam-pattern",
        "asset.function.graph-representation",
        "asset.function.one-input-two-outputs-non-example",
      ],
      pedagogicalLayers: ["exam-patterns"],
      deliveryRequirements: ["displayed-text", "displayed-notation"],
      learnerInteractionRequirements: ["practice-input"],
      expectedEvidenceTypes: ["practice-attempt"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.inverse-function.reflection",
      title: "Reflect on reversing an input-output relationship",
      intent: "reflection",
      targetConceptIds: ["concept.inverse-function"],
      knowledgeAssetIds: ["asset.inverse-function.reverse-mapping-representation"],
      pedagogicalLayers: ["intuition"],
      deliveryRequirements: ["displayed-text"],
      learnerInteractionRequirements: ["reflection"],
      expectedEvidenceTypes: ["reflection"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.domain-range.exam-pattern",
      title: "Domain and range recognition pattern",
      intent: "exam-patterns",
      targetConceptIds: ["concept.domain-range"],
      knowledgeAssetIds: [
        "asset.function.domain-range-exam-pattern",
        "asset.domain-range.graph-representation",
      ],
      pedagogicalLayers: ["exam-patterns"],
      deliveryRequirements: ["displayed-text", "displayed-notation"],
      learnerInteractionRequirements: ["practice-input"],
      expectedEvidenceTypes: ["practice-attempt"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.domain-range.intuition-permitted-inputs",
      title: "Domain and range through what a rule will accept",
      intent: "intuition",
      targetConceptIds: ["concept.domain-range"],
      knowledgeAssetIds: [
        "asset.domain-range.accepted-input-representation",
        "asset.domain-range.mapping-representation",
        "asset.domain-range.table-representation",
      ],
      pedagogicalLayers: ["intuition"],
      deliveryRequirements: ["displayed-text"],
      learnerInteractionRequirements: ["reflection"],
      expectedEvidenceTypes: ["reflection"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.domain-range.low-energy-core-insight",
      title: "Domain and range core insight",
      intent: "low-energy",
      targetConceptIds: ["concept.domain-range"],
      knowledgeAssetIds: [
        "asset.domain-range.accepted-input-representation",
      ],
      pedagogicalLayers: ["intuition"],
      deliveryRequirements: ["displayed-text"],
      learnerInteractionRequirements: [],
      expectedEvidenceTypes: [],
      completionSemantics: { requiresLearnerInteraction: false, evidenceRequiredForCompletion: false },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.domain-range.reflection",
      title: "Reflect on which inputs a rule will accept",
      intent: "reflection",
      targetConceptIds: ["concept.domain-range"],
      knowledgeAssetIds: [
        "asset.domain-range.accepted-input-representation",
        "asset.domain-range.ticket-application",
      ],
      pedagogicalLayers: ["intuition"],
      deliveryRequirements: ["displayed-text"],
      learnerInteractionRequirements: ["reflection"],
      expectedEvidenceTypes: ["reflection"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.domain-range.mechanics-stating-domain",
      title: "Stating a domain and a range",
      intent: "mechanics",
      targetConceptIds: ["concept.domain-range"],
      knowledgeAssetIds: [
        "asset.domain-range.interval-representation",
        "asset.domain-range.square-root-example",
        "asset.domain-range.division-non-example",
        "asset.domain-range.stating-domain-procedure",
        "asset.domain-range.range-misconception",
      ],
      pedagogicalLayers: ["mechanics"],
      deliveryRequirements: ["displayed-text", "displayed-notation"],
      learnerInteractionRequirements: ["reflection"],
      expectedEvidenceTypes: ["reflection"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.domain-range.practice-stating-domain",
      title: "Practise stating a domain",
      intent: "practice",
      targetConceptIds: ["concept.domain-range"],
      knowledgeAssetIds: [
        "asset.domain-range.square-root-example",
        "asset.domain-range.division-non-example",
      ],
      pedagogicalLayers: ["mechanics"],
      deliveryRequirements: ["displayed-text", "displayed-notation", "typed-input"],
      learnerInteractionRequirements: ["practice-input"],
      expectedEvidenceTypes: ["practice-attempt"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.inverse-function.intuition-undoing",
      title: "Inverses through undoing what a rule did",
      intent: "intuition",
      targetConceptIds: ["concept.inverse-function"],
      knowledgeAssetIds: [
        "asset.inverse-function.undo-representation",
        "asset.inverse-function.table-representation",
        "asset.inverse-function.doubling-halving-example",
        "asset.inverse-function.currency-application",
      ],
      pedagogicalLayers: ["intuition"],
      deliveryRequirements: ["displayed-text"],
      learnerInteractionRequirements: ["reflection"],
      expectedEvidenceTypes: ["reflection"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.inverse-function.low-energy-core-insight",
      title: "Inverse function core insight",
      intent: "low-energy",
      targetConceptIds: ["concept.inverse-function"],
      knowledgeAssetIds: [
        "asset.inverse-function.undo-representation",
      ],
      pedagogicalLayers: ["intuition"],
      deliveryRequirements: ["displayed-text"],
      learnerInteractionRequirements: [],
      expectedEvidenceTypes: [],
      completionSemantics: { requiresLearnerInteraction: false, evidenceRequiredForCompletion: false },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.inverse-function.mechanics-finding-inverse",
      title: "Finding an inverse and reading its notation",
      intent: "mechanics",
      targetConceptIds: ["concept.inverse-function"],
      knowledgeAssetIds: [
        "asset.inverse-function.notation-representation",
        "asset.inverse-function.finding-inverse-procedure",
        "asset.inverse-function.squaring-non-example",
        "asset.inverse-function.reciprocal-misconception",
      ],
      pedagogicalLayers: ["mechanics"],
      deliveryRequirements: ["displayed-text", "displayed-notation"],
      learnerInteractionRequirements: ["reflection"],
      expectedEvidenceTypes: ["reflection"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.inverse-function.practice-finding-inverse",
      title: "Practise finding an inverse",
      intent: "practice",
      targetConceptIds: ["concept.inverse-function"],
      knowledgeAssetIds: [
        "asset.inverse-function.doubling-halving-example",
        "asset.inverse-function.finding-inverse-procedure",
      ],
      pedagogicalLayers: ["mechanics"],
      deliveryRequirements: ["displayed-text", "displayed-notation", "typed-input"],
      learnerInteractionRequirements: ["practice-input"],
      expectedEvidenceTypes: ["practice-attempt"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.inverse-function.exam-pattern",
      title: "Exam pattern: find an inverse",
      intent: "exam-patterns",
      targetConceptIds: ["concept.inverse-function"],
      knowledgeAssetIds: [
        "asset.inverse-function.exam-pattern",
        "asset.inverse-function.reflection-line-representation",
      ],
      pedagogicalLayers: ["exam-patterns"],
      deliveryRequirements: ["displayed-text", "displayed-notation"],
      learnerInteractionRequirements: ["practice-input"],
      expectedEvidenceTypes: ["practice-attempt"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
  ],
});
