import {
  concept,
  conceptRelationship,
  knowledgeAsset,
  knowledgeCatalog,
  learningExperience,
  mathematicsDomain,
  topic,
} from "../domain/mathematical-knowledge.js";

/**
 * Minimal seed data only. It proves the headless knowledge model with stable
 * identifiers, relationships, assets, and experiences; it is not a migration
 * of the existing content library or a presentation-oriented content file.
 */
export const functionsSeedKnowledge = knowledgeCatalog({
  domains: [
    mathematicsDomain({
      id: "mathematics.school-foundations",
      title: "School Mathematics Foundations",
      description: "Seed mathematical scope for exploring foundational function concepts.",
      version: "math-lumina.seed.v1",
    }),
  ],
  topics: [
    topic({
      id: "topic.functions",
      domainId: "mathematics.school-foundations",
      title: "Functions",
      description: "Seed topic for relationships between inputs, outputs, and functional rules.",
      version: "math-lumina.seed.v1",
    }),
  ],
  concepts: [
    concept({
      id: "concept.function",
      topicId: "topic.functions",
      title: "What is a Function?",
      conceptualDescription: "A function associates each permitted input with one output according to a rule.",
      version: "math-lumina.seed.v1",
    }),
    concept({
      id: "concept.domain-range",
      topicId: "topic.functions",
      title: "Domain and Range",
      conceptualDescription: "The domain describes permitted inputs and the range describes outputs produced by a function.",
      version: "math-lumina.seed.v1",
    }),
    concept({
      id: "concept.inverse-function",
      topicId: "topic.functions",
      title: "Inverse Functions",
      conceptualDescription: "An inverse function reverses the input-output relationship when an inverse exists.",
      version: "math-lumina.seed.v1",
    }),
  ],
  relationships: [
    conceptRelationship({
      id: "relationship.function-prerequisite-domain-range",
      kind: "prerequisite",
      sourceConceptId: "concept.function",
      targetConceptId: "concept.domain-range",
      rationale: "Understanding the input-output role of a function provides useful context for domain and range.",
      version: "math-lumina.seed.v1",
    }),
    conceptRelationship({
      id: "relationship.function-bridge-inverse-function",
      kind: "concept-bridge",
      sourceConceptId: "concept.function",
      targetConceptId: "concept.inverse-function",
      rationale: "The input-output relationship can later be connected to the idea of reversing a relationship.",
      version: "math-lumina.seed.v1",
    }),
  ],
  assets: [
    knowledgeAsset({
      id: "asset.function.vending-machine-representation",
      kind: "representation",
      title: "Function as a vending machine",
      content: "Imagine a vending machine: an input selection goes in and one output item comes out according to the machine's rule.",
      conceptIds: ["concept.function"],
      supportedLayers: ["intuition"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.function.input-output-example",
      kind: "example",
      title: "A rule that doubles an input",
      content: "For the rule f(x) = 2x, input 3 produces output 6.",
      conceptIds: ["concept.function"],
      supportedLayers: ["intuition", "mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.function.one-input-two-outputs-non-example",
      kind: "non-example",
      title: "One input with two outputs",
      content: "A relation that gives the same input two different outputs does not meet the defining function condition.",
      conceptIds: ["concept.function"],
      supportedLayers: ["intuition", "mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.function.notation-procedure",
      kind: "procedure",
      title: "Reading function notation",
      content: "Read f(x) = 2x + 3 as: take x, multiply by 2, then add 3.",
      conceptIds: ["concept.function"],
      supportedLayers: ["mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.function.input-output-misconception",
      kind: "misconception",
      title: "Function rule versus one-to-one rule",
      content: "Different inputs may share an output; the defining condition concerns each input having one output.",
      conceptIds: ["concept.function"],
      supportedLayers: ["intuition", "mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.function.temperature-application",
      kind: "application",
      title: "Temperature conversion",
      content: "A conversion rule can associate a temperature in one unit with a temperature in another unit.",
      conceptIds: ["concept.function"],
      supportedLayers: ["intuition"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.function.domain-range-exam-pattern",
      kind: "exam-pattern",
      title: "Recognising a domain-and-range question",
      content: "When asked for domain and range, identify permitted inputs separately from outputs produced by the relation.",
      conceptIds: ["concept.domain-range"],
      supportedLayers: ["exam-patterns"],
      version: "math-lumina.seed.v1",
    }),
  ],
  experiences: [
    learningExperience({
      id: "experience.function.intuition-vending-machine",
      title: "Function intuition through an input-output machine",
      intent: "intuition",
      targetConceptIds: ["concept.function"],
      knowledgeAssetIds: [
        "asset.function.vending-machine-representation",
        "asset.function.input-output-example",
      ],
      pedagogicalLayers: ["intuition"],
      deliveryRequirements: ["displayed-text"],
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.function.low-energy-core-insight",
      title: "Function core insight",
      intent: "low-energy",
      targetConceptIds: ["concept.function"],
      knowledgeAssetIds: ["asset.function.vending-machine-representation"],
      pedagogicalLayers: ["intuition"],
      deliveryRequirements: ["displayed-text"],
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.function.mechanics-notation",
      title: "Function notation and mechanics",
      intent: "mechanics",
      targetConceptIds: ["concept.function"],
      knowledgeAssetIds: [
        "asset.function.input-output-example",
        "asset.function.notation-procedure",
        "asset.function.one-input-two-outputs-non-example",
      ],
      pedagogicalLayers: ["mechanics"],
      deliveryRequirements: ["displayed-text", "displayed-notation"],
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.domain-range.exam-pattern",
      title: "Domain and range recognition pattern",
      intent: "exam-patterns",
      targetConceptIds: ["concept.domain-range"],
      knowledgeAssetIds: ["asset.function.domain-range-exam-pattern"],
      pedagogicalLayers: ["exam-patterns"],
      deliveryRequirements: ["displayed-text", "displayed-notation"],
      version: "math-lumina.seed.v1",
    }),
  ],
});
