import {
  concept,
  conceptRelationship,
  knowledgeAsset,
  knowledgeCatalog,
  learningExperience,
  mathematicsDomain,
  topic,
} from "../domain/mathematical-knowledge.js";

/**
 * A deliberately small, published Functions graph. It proves stable identity,
 * typed relationships, version-aware knowledge resolution, representations,
 * misconception assets, bridges, and all three pedagogical layers. It is not a
 * curriculum-management system or a full mathematics catalogue.
 */
export const functionsSeedKnowledge = knowledgeCatalog({
  domains: [
    mathematicsDomain({
      id: "mathematics.school-foundations",
      title: "School Mathematics Foundations",
      description: "Seed mathematical scope for foundational function concepts.",
      version: "math-lumina.seed.v1",
    }),
  ],
  topics: [
    topic({
      id: "topic.functions",
      domainId: "mathematics.school-foundations",
      title: "Functions",
      description: "Seed topic for relationships between inputs, outputs, and functional rules.",
      version: "math-lumina.seed.v1",
    }),
  ],
  concepts: [
    concept({
      id: "concept.function",
      topicId: "topic.functions",
      title: "What is a Function?",
      conceptualDescription: "A function associates each permitted input with one output according to a rule.",
      version: "math-lumina.seed.v1",
    }),
    concept({
      id: "concept.domain-range",
      topicId: "topic.functions",
      title: "Domain and Range",
      conceptualDescription: "The domain describes permitted inputs and the range describes outputs produced by a function.",
      version: "math-lumina.seed.v1",
    }),
    concept({
      id: "concept.inverse-function",
      topicId: "topic.functions",
      title: "Inverse Functions",
      conceptualDescription: "An inverse function reverses an input-output relationship when an inverse exists.",
      version: "math-lumina.seed.v1",
    }),
  ],
  relationships: [
    conceptRelationship({
      id: "relationship.function-prerequisite-domain-range",
      kind: "prerequisite",
      sourceConceptId: "concept.function",
      targetConceptId: "concept.domain-range",
      rationale: "The input-output role of a function is useful context before exploring domain and range.",
      version: "math-lumina.seed.v1",
    }),
    conceptRelationship({
      id: "relationship.function-related-domain-range",
      kind: "related",
      sourceConceptId: "concept.function",
      targetConceptId: "concept.domain-range",
      rationale: "Domain and range describe the inputs and outputs of a function relationship.",
      version: "math-lumina.seed.v1",
    }),
    conceptRelationship({
      id: "relationship.function-bridge-inverse-function",
      kind: "concept-bridge",
      sourceConceptId: "concept.function",
      targetConceptId: "concept.inverse-function",
      rationale: "An input-output relationship can later be connected to reversing a relationship.",
      version: "math-lumina.seed.v1",
    }),
  ],
  assets: [
    knowledgeAsset({
      id: "asset.function.vending-machine-representation",
      kind: "representation",
      representationForm: "contextual",
      title: "Function as a vending machine",
      content: "An input selection goes into a vending machine and one output item comes out according to the machine's rule.",
      conceptIds: ["concept.function"],
      supportedLayers: ["intuition"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.function.mapping-representation",
      kind: "representation",
      representationForm: "visual",
      title: "Input-output mapping arrows",
      content: "A mapping representation can show each input arrow pointing to one output, without requiring a visual component.",
      conceptIds: ["concept.function"],
      supportedLayers: ["intuition", "mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.function.rule-representation",
      kind: "representation",
      representationForm: "symbolic",
      title: "Function rule notation",
      content: "The symbolic representation f(x) = 2x describes an output rule for each input x.",
      conceptIds: ["concept.function"],
      supportedLayers: ["mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.function.table-representation",
      kind: "representation",
      representationForm: "numerical",
      title: "Input-output value table",
      content: "A numerical table can pair inputs 1, 2, 3 with outputs 2, 4, 6 for the rule f(x) = 2x.",
      conceptIds: ["concept.function"],
      supportedLayers: ["intuition", "mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.function.graph-representation",
      kind: "representation",
      representationForm: "graphical",
      title: "Graphical function representation",
      content: "A graph can represent how x-values and y-values are paired for a rule, independently of any chart component.",
      conceptIds: ["concept.function"],
      supportedLayers: ["mechanics", "exam-patterns"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.function.input-output-example",
      kind: "example",
      title: "A rule that doubles an input",
      content: "For the rule f(x) = 2x, input 3 produces output 6.",
      conceptIds: ["concept.function"],
      supportedLayers: ["intuition", "mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.function.one-input-two-outputs-non-example",
      kind: "non-example",
      title: "One input with two outputs",
      content: "A relation that gives the same input two different outputs does not meet the defining function condition.",
      conceptIds: ["concept.function"],
      supportedLayers: ["intuition", "mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.function.notation-procedure",
      kind: "procedure",
      title: "Reading function notation",
      content: "Read f(x) = 2x + 3 as: take x, multiply by 2, then add 3.",
      conceptIds: ["concept.function"],
      supportedLayers: ["mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.function.input-output-misconception",
      kind: "misconception",
      title: "Function rule versus one-to-one rule",
      content: "Different inputs may share an output; the defining condition concerns each input having one output.",
      conceptIds: ["concept.function"],
      supportedLayers: ["intuition", "mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.function.temperature-application",
      kind: "application",
      title: "Temperature conversion",
      content: "A conversion rule can associate a temperature in one unit with a temperature in another unit.",
      conceptIds: ["concept.function"],
      supportedLayers: ["intuition"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.function.identifying-function-exam-pattern",
      kind: "exam-pattern",
      title: "Recognising a function-definition question",
      content: "When deciding whether a relation is a function, examine whether any input is paired with more than one output.",
      conceptIds: ["concept.function"],
      supportedLayers: ["exam-patterns"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.function.domain-range-exam-pattern",
      kind: "exam-pattern",
      title: "Recognising a domain-and-range question",
      content: "When asked for domain and range, identify permitted inputs separately from outputs produced by the relation.",
      conceptIds: ["concept.domain-range"],
      supportedLayers: ["exam-patterns"],
      version: "math-lumina.seed.v1",
    }),
  ],
  experiences: [
    learningExperience({
      id: "experience.function.intuition-vending-machine",
      title: "Function intuition through an input-output machine",
      intent: "intuition",
      targetConceptIds: ["concept.function"],
      knowledgeAssetIds: ["asset.function.vending-machine-representation", "asset.function.input-output-example"],
      pedagogicalLayers: ["intuition"],
      deliveryRequirements: ["displayed-text"],
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.function.low-energy-core-insight",
      title: "Function core insight",
      intent: "low-energy",
      targetConceptIds: ["concept.function"],
      knowledgeAssetIds: ["asset.function.vending-machine-representation"],
      pedagogicalLayers: ["intuition"],
      deliveryRequirements: ["displayed-text"],
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.function.practice-input-output",
      title: "Practise tracing an input-output rule",
      intent: "practice",
      targetConceptIds: ["concept.function"],
      knowledgeAssetIds: ["asset.function.input-output-example"],
      pedagogicalLayers: ["intuition"],
      deliveryRequirements: ["displayed-text", "typed-input"],
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.function.mechanics-notation",
      title: "Function notation and mechanics",
      intent: "mechanics",
      targetConceptIds: ["concept.function"],
      knowledgeAssetIds: [
        "asset.function.rule-representation",
        "asset.function.input-output-example",
        "asset.function.notation-procedure",
        "asset.function.one-input-two-outputs-non-example",
      ],
      pedagogicalLayers: ["mechanics"],
      deliveryRequirements: ["displayed-text", "displayed-notation"],
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.function.exam-patterns-identifying-function",
      title: "Exam pattern: identify a function relation",
      intent: "exam-patterns",
      targetConceptIds: ["concept.function"],
      knowledgeAssetIds: ["asset.function.identifying-function-exam-pattern", "asset.function.one-input-two-outputs-non-example"],
      pedagogicalLayers: ["exam-patterns"],
      deliveryRequirements: ["displayed-text", "displayed-notation"],
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.domain-range.exam-pattern",
      title: "Domain and range recognition pattern",
      intent: "exam-patterns",
      targetConceptIds: ["concept.domain-range"],
      knowledgeAssetIds: ["asset.function.domain-range-exam-pattern"],
      pedagogicalLayers: ["exam-patterns"],
      deliveryRequirements: ["displayed-text", "displayed-notation"],
      version: "math-lumina.seed.v1",
    }),
  ],
});
