import {
  concept,
  conceptRelationship,
  knowledgeAsset,
  learningExperience,
  topic,
} from "../domain/mathematical-knowledge.js";
import { TopicSeed } from "./topic-seed.js";

/**
 * Patterns and sequences: four concepts, and the reason this topic is here
 * rather than another one.
 *
 * A second topic was needed so that a learner has somewhere to go after
 * functions. Almost any topic would have satisfied that. This one was chosen
 * because it is the same idea wearing different notation -- a sequence hands
 * back one term for each position, which is what a function does with an input
 * -- so the bridge between the two topics carries real content instead of being
 * an edge added to satisfy a graph check.
 *
 * `concept.sequence-as-function` is where that bridge is spent, and it is the
 * only concept here that exists to connect rather than to introduce. It also
 * carries the distinction that makes the connection honest: a sequence is
 * defined at position 1, 2, 3 and nowhere between them, so its graph is
 * separated points and not a line, and there is no such thing as the 2.5th
 * term. A bridge that hid that would be teaching something false in order to
 * look tidy.
 *
 * This content was AI-drafted and is human-committed. `AUTHORSHIP.md` in this
 * directory records what that means and what a person is committing to --
 * chiefly that no test here checks whether the mathematics is correct.
 *
 * Money is in rands and contexts are local, because the learner this is written
 * for is in a South African school.
 */
export const sequencesTopicSeed: TopicSeed = {
  topic: topic({
    id: "topic.sequences",
    domainId: "mathematics.school-foundations",
    title: "Patterns and Sequences",
    description: "Ordered lists of numbers, the rules that decide them, and how a position determines a term.",
    version: "math-lumina.seed.v1",
  }),
  concepts: [
    concept({
      id: "concept.number-pattern",
      topicId: "topic.sequences",
      title: "Seeing the Rule in a Pattern",
      conceptualDescription: "A sequence is an ordered list of numbers, and the useful question is what decides the next one.",
      version: "math-lumina.seed.v1",
    }),
    concept({
      id: "concept.arithmetic-sequence",
      topicId: "topic.sequences",
      title: "Patterns That Grow by the Same Amount",
      conceptualDescription: "When every term is the one before it plus a fixed amount, the position alone is enough to work out the term.",
      version: "math-lumina.seed.v1",
    }),
    concept({
      id: "concept.quadratic-sequence",
      topicId: "topic.sequences",
      title: "Patterns Whose Growth Itself Grows",
      conceptualDescription: "When the gaps between terms are not constant but the gaps between those gaps are, the pattern is quadratic.",
      version: "math-lumina.seed.v1",
    }),
    concept({
      id: "concept.sequence-as-function",
      topicId: "topic.sequences",
      title: "A Pattern Is a Rule in Disguise",
      conceptualDescription: "A sequence gives one term for each position, which is exactly what a function does: the position is the input and the term is the output.",
      version: "math-lumina.seed.v1",
    }),
  ],
  relationships: [
    conceptRelationship({
      id: "relationship.number-pattern-prerequisite-arithmetic-sequence",
      kind: "prerequisite",
      sourceConceptId: "concept.number-pattern",
      targetConceptId: "concept.arithmetic-sequence",
      rationale: "Asking what decides the next term comes before naming the case where the answer is a fixed amount.",
      version: "math-lumina.seed.v1",
    }),
    conceptRelationship({
      id: "relationship.number-pattern-related-quadratic-sequence",
      kind: "related",
      sourceConceptId: "concept.number-pattern",
      targetConceptId: "concept.quadratic-sequence",
      rationale: "Looking at the gaps between terms is the same first move, whether or not those gaps turn out to be constant.",
      version: "math-lumina.seed.v1",
    }),
    conceptRelationship({
      id: "relationship.arithmetic-sequence-prerequisite-quadratic-sequence",
      kind: "prerequisite",
      sourceConceptId: "concept.arithmetic-sequence",
      targetConceptId: "concept.quadratic-sequence",
      rationale: "A second difference is a constant difference found one level down, so the constant case is worth meeting first.",
      version: "math-lumina.seed.v1",
    }),
    conceptRelationship({
      id: "relationship.number-pattern-prerequisite-sequence-as-function",
      kind: "prerequisite",
      sourceConceptId: "concept.number-pattern",
      targetConceptId: "concept.sequence-as-function",
      rationale: "Position and term have to be separate ideas before one can be called an input and the other an output.",
      version: "math-lumina.seed.v1",
    }),
    conceptRelationship({
      id: "relationship.arithmetic-sequence-bridge-sequence-as-function",
      kind: "concept-bridge",
      sourceConceptId: "concept.arithmetic-sequence",
      targetConceptId: "concept.sequence-as-function",
      rationale: "A rule for the nth term is already written as a rule taking n, which is the whole of the connection to functions.",
      version: "math-lumina.seed.v1",
    }),
  ],
  assets: [
    // -----------------------------------------------------------------------
    // concept.number-pattern
    // -----------------------------------------------------------------------
    knowledgeAsset({
      id: "asset.number-pattern.paving-representation",
      kind: "representation",
      representationForm: "contextual",
      title: "A path being paved",
      content: "A path is laid one row at a time. The first row takes 3 stones, the second takes 5, the third takes 7. The list 3, 5, 7 is the pattern, and the question is what the builder does for the next row.",
      conceptIds: ["concept.number-pattern"],
      supportedLayers: ["intuition"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.number-pattern.term-notation-representation",
      kind: "representation",
      representationForm: "symbolic",
      title: "Naming terms by position",
      content: "T1 is the first term, T2 the second, and Tn the term in position n. The subscript is a position, never a value: in 3, 5, 7 the term T2 is 5.",
      conceptIds: ["concept.number-pattern"],
      supportedLayers: ["mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.number-pattern.position-table-representation",
      kind: "representation",
      representationForm: "numerical",
      title: "Positions beside terms",
      content: "Positions 1, 2, 3, 4 written above the terms 3, 5, 7, 9 keeps the two apart. The gaps below, 2, 2, 2, are what most rules are found from.",
      conceptIds: ["concept.number-pattern"],
      supportedLayers: ["intuition", "mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.number-pattern.next-term-example",
      kind: "example",
      title: "Continuing 3, 5, 7",
      content: "The gap from 3 to 5 is 2, and from 5 to 7 is 2. Continuing with the same gap gives 9, then 11.",
      conceptIds: ["concept.number-pattern"],
      supportedLayers: ["intuition", "mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.number-pattern.stated-rule-non-example",
      kind: "non-example",
      title: "A list is not yet a rule",
      content: "Any finite list can be continued in more than one way. 2, 4, 8 continues as 16 under doubling and as 14 under adding the gaps 2, 4, 6. A pattern is a claim about the rule, so the rule has to be stated rather than assumed from the numbers alone.",
      conceptIds: ["concept.number-pattern"],
      supportedLayers: ["intuition", "mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.number-pattern.finding-gaps-procedure",
      kind: "procedure",
      title: "Looking at the gaps first",
      content: "Write the terms in a row. Under each pair, write the second term minus the first. If those gaps are all the same, the pattern adds a fixed amount each time. If they are not, look at the gaps between the gaps.",
      conceptIds: ["concept.number-pattern"],
      supportedLayers: ["mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.number-pattern.three-terms-misconception",
      kind: "misconception",
      title: "Treating three terms as proof",
      content: "Three terms that fit a rule are often taken as settling it. They narrow the possibilities and do not close them, which is why a question usually says what kind of pattern it is.",
      conceptIds: ["concept.number-pattern"],
      supportedLayers: ["intuition", "mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.number-pattern.savings-application",
      kind: "application",
      title: "Money put away each week",
      content: "R150 is put away in week one and R80 in every week after. The total saved by the end of each week goes 150, 230, 310, 390, and the position in the list is the week number. The weekly amounts are 150, 80, 80, 80 -- a different list, and worth keeping apart from the running total.",
      conceptIds: ["concept.number-pattern"],
      supportedLayers: ["intuition", "exam-patterns"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.number-pattern.exam-pattern",
      kind: "exam-pattern",
      title: "Exam pattern: write down the next two terms",
      content: "A question gives four or five terms and asks for the next two and for the rule in words. Marks are usually for the rule, not only for the numbers, so the gap being found should be said out loud.",
      conceptIds: ["concept.number-pattern"],
      supportedLayers: ["exam-patterns"],
      version: "math-lumina.seed.v1",
    }),

    // -----------------------------------------------------------------------
    // concept.arithmetic-sequence
    // -----------------------------------------------------------------------
    knowledgeAsset({
      id: "asset.arithmetic-sequence.stacked-chairs-representation",
      kind: "representation",
      representationForm: "contextual",
      title: "Chairs stacked on top of each other",
      content: "One chair stands 90 cm high. Every chair stacked on it adds 8 cm. The height of the stack goes 90, 98, 106, and the same 8 cm is added no matter how tall the stack already is.",
      conceptIds: ["concept.arithmetic-sequence"],
      supportedLayers: ["intuition"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.arithmetic-sequence.general-term-representation",
      kind: "representation",
      representationForm: "symbolic",
      title: "The rule for the nth term",
      content: "Tn = a + (n - 1)d, where a is the first term and d is the fixed amount added each time. The (n - 1) is there because the first term has had d added to it no times.",
      conceptIds: ["concept.arithmetic-sequence"],
      supportedLayers: ["mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.arithmetic-sequence.difference-table-representation",
      kind: "representation",
      representationForm: "numerical",
      title: "A row of gaps that are all the same",
      content: "For 7, 11, 15, 19 the gaps are 4, 4, 4. One repeated number on the gap row is what makes the pattern arithmetic, and that number is d.",
      conceptIds: ["concept.arithmetic-sequence"],
      supportedLayers: ["intuition", "mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.arithmetic-sequence.evenly-spaced-representation",
      kind: "representation",
      representationForm: "graphical",
      title: "Terms plotted against their positions",
      content: "Plotting position along the bottom and term up the side puts the points of an arithmetic sequence in a straight line, evenly spaced, with the gap d showing as the rise from one point to the next.",
      conceptIds: ["concept.arithmetic-sequence"],
      supportedLayers: ["mechanics", "exam-patterns"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.arithmetic-sequence.finding-term-example",
      kind: "example",
      title: "The fiftieth term without writing fifty terms",
      content: "For 7, 11, 15 the first term a is 7 and d is 4. T50 = 7 + 49 x 4 = 203, found without listing anything in between.",
      conceptIds: ["concept.arithmetic-sequence"],
      supportedLayers: ["mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.arithmetic-sequence.doubling-non-example",
      kind: "non-example",
      title: "A pattern that multiplies instead",
      content: "3, 6, 12, 24 has gaps 3, 6, 12, which are not the same. Each term is double the one before, so there is a rule and it is not a fixed amount added, and Tn = a + (n - 1)d does not describe it.",
      conceptIds: ["concept.arithmetic-sequence"],
      supportedLayers: ["intuition", "mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.arithmetic-sequence.finding-rule-procedure",
      kind: "procedure",
      title: "Writing the rule from the terms",
      content: "Take the first term as a. Subtract any term from the one after it to get d. Substitute both into Tn = a + (n - 1)d, then check the rule against a term you were given but did not use.",
      conceptIds: ["concept.arithmetic-sequence"],
      supportedLayers: ["mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.arithmetic-sequence.off-by-one-misconception",
      kind: "misconception",
      title: "Adding d one time too many",
      content: "Tn = a + nd is a common form to reach for, and it gives the term after the one asked for. Checking the rule at n = 1, where it must return the first term, catches it every time.",
      conceptIds: ["concept.arithmetic-sequence"],
      supportedLayers: ["mechanics", "exam-patterns"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.arithmetic-sequence.repayment-application",
      kind: "application",
      title: "Paying off a fixed amount",
      content: "R4 800 is owed and R400 is paid every month. What is still owed after each payment goes 4 400, 4 000, 3 600, an arithmetic sequence with d = -400, and the month the debt reaches zero is a question about position.",
      conceptIds: ["concept.arithmetic-sequence"],
      supportedLayers: ["intuition", "exam-patterns"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.arithmetic-sequence.exam-pattern",
      kind: "exam-pattern",
      title: "Exam pattern: find Tn, then use it backwards",
      content: "A question asks for the general term, then for a term at a large position, then which position holds a given value. The last part is the general term set equal to that value and solved for n, and a fractional n means the value is not in the sequence.",
      conceptIds: ["concept.arithmetic-sequence"],
      supportedLayers: ["exam-patterns"],
      version: "math-lumina.seed.v1",
    }),

    // -----------------------------------------------------------------------
    // concept.quadratic-sequence
    // -----------------------------------------------------------------------
    knowledgeAsset({
      id: "asset.quadratic-sequence.growing-square-representation",
      kind: "representation",
      representationForm: "contextual",
      title: "Squares of tiles, each one bigger",
      content: "Tiles laid as squares take 1, 4, 9, 16 tiles. Each square needs more extra tiles than the one before it did: 3, then 5, then 7. The pattern grows, and the growth grows too.",
      conceptIds: ["concept.quadratic-sequence"],
      supportedLayers: ["intuition"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.quadratic-sequence.second-difference-representation",
      kind: "representation",
      representationForm: "numerical",
      title: "Two rows of gaps",
      content: "For 1, 4, 9, 16 the first row of gaps is 3, 5, 7 and the row under that is 2, 2. A repeated number on the second row is what makes a pattern quadratic.",
      conceptIds: ["concept.quadratic-sequence"],
      supportedLayers: ["intuition", "mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.quadratic-sequence.general-term-representation",
      kind: "representation",
      representationForm: "symbolic",
      title: "The nth term of a quadratic pattern",
      content: "Tn = an^2 + bn + c. The second difference is 2a, so a is half of it, and b and c are then found by making the rule agree with the first two terms.",
      conceptIds: ["concept.quadratic-sequence"],
      supportedLayers: ["mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.quadratic-sequence.curving-points-representation",
      kind: "representation",
      representationForm: "graphical",
      title: "Terms that bend away from a line",
      content: "Plotting position against term for a quadratic sequence gives points that curve. Any straight edge laid along the first two points leaves the rest above or below it, which is the visible sign that the gaps are changing.",
      conceptIds: ["concept.quadratic-sequence"],
      supportedLayers: ["mechanics", "exam-patterns"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.quadratic-sequence.finding-rule-example",
      kind: "example",
      title: "Working out a rule for 3, 8, 15, 24",
      content: "First gaps 5, 7, 9; second gap 2, so a = 1. Then T1 = 1 + b + c = 3 and T2 = 4 + 2b + c = 8. Subtracting the first from the second leaves b = 2, and c = 0 follows. So Tn = n^2 + 2n, and checking T4 gives 16 + 8 = 24.",
      conceptIds: ["concept.quadratic-sequence"],
      supportedLayers: ["mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.quadratic-sequence.arithmetic-non-example",
      kind: "non-example",
      title: "A pattern whose second differences are zero",
      content: "For 5, 9, 13, 17 the first gaps are 4, 4, 4 and the second gaps are 0, 0. The pattern is arithmetic, and forcing it into an^2 + bn + c gives a = 0, which is the same rule written the long way round.",
      conceptIds: ["concept.quadratic-sequence"],
      supportedLayers: ["mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.quadratic-sequence.building-rule-procedure",
      kind: "procedure",
      title: "From two rows of gaps to a rule",
      content: "Write the first differences, then the second differences. Halve the second difference to get a. The first two terms then give two equations: a + b + c = T1 and 4a + 2b + c = T2. Subtracting the first from the second leaves 3a + b = T2 - T1, so b comes out on its own, and c is whatever is left of T1 once a and b are taken off. None of this assumes the pattern is growing: a second difference of -2 gives a = -1, the same steps follow unchanged, and the terms turn downward instead of upward.",
      conceptIds: ["concept.quadratic-sequence"],
      supportedLayers: ["mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.quadratic-sequence.doubling-misconception",
      kind: "misconception",
      title: "Reading growing gaps as doubling",
      content: "A pattern whose gaps are getting bigger is often described as doubling. Doubling multiplies, and a quadratic pattern adds a growing amount, so the two come apart quickly: 1, 4, 9, 16 against 1, 2, 4, 8.",
      conceptIds: ["concept.quadratic-sequence"],
      supportedLayers: ["intuition", "mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.quadratic-sequence.seating-application",
      kind: "application",
      title: "Seats in a hall that widens as it goes back",
      content: "A hall has 12 seats in the front row and every row behind it has two more seats than the row in front of it. The rows themselves go 12, 14, 16, 18. The running total goes 12, 26, 42, 60, whose gaps are 14, 16, 18 and whose second gaps are 2, so the total is a quadratic sequence -- which is why it is not simply rows times seats.",
      conceptIds: ["concept.quadratic-sequence"],
      supportedLayers: ["intuition", "exam-patterns"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.quadratic-sequence.exam-pattern",
      kind: "exam-pattern",
      title: "Exam pattern: two rows of differences, then the rule",
      content: "A question gives four terms, asks for the next one, then for the general term, then for a term far along. Writing both rows of differences before touching an^2 + bn + c is what makes the rest of the question routine.",
      conceptIds: ["concept.quadratic-sequence"],
      supportedLayers: ["exam-patterns"],
      version: "math-lumina.seed.v1",
    }),

    // -----------------------------------------------------------------------
    // concept.sequence-as-function
    // -----------------------------------------------------------------------
    knowledgeAsset({
      id: "asset.sequence-as-function.position-as-input-representation",
      kind: "representation",
      representationForm: "contextual",
      title: "Ask the pattern for a position and it answers",
      content: "Asking a pattern for its tenth term is asking a question and getting one answer back. Asking a function for f(10) is the same act with different notation, and a pattern that gave two different tenth terms would be as broken as a function that gave two outputs for one input.",
      conceptIds: ["concept.sequence-as-function"],
      supportedLayers: ["intuition"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.sequence-as-function.notation-representation",
      kind: "representation",
      representationForm: "symbolic",
      title: "Tn and f(n) say the same thing",
      content: "Tn = 4n - 1 and f(n) = 4n - 1 describe the same rule. The only difference is that a sequence is asked about counting positions 1, 2, 3, so its domain is those positions and nothing else.",
      conceptIds: ["concept.sequence-as-function"],
      supportedLayers: ["mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.sequence-as-function.mapping-table-representation",
      kind: "representation",
      representationForm: "numerical",
      title: "Positions in, terms out",
      content: "The table 1 to 3, 2 to 7, 3 to 11, 4 to 15 is a sequence read left to right and a function read as input to output. Neither reading changes a single number in it.",
      conceptIds: ["concept.sequence-as-function"],
      supportedLayers: ["intuition", "mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.sequence-as-function.separated-points-representation",
      kind: "representation",
      representationForm: "graphical",
      title: "Points that are not joined up",
      content: "A sequence plotted against position gives separated dots. They may sit along a line, and the line is not part of the sequence, because there is no position between the third and the fourth and therefore no term there.",
      conceptIds: ["concept.sequence-as-function"],
      supportedLayers: ["mechanics", "exam-patterns"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.sequence-as-function.arithmetic-is-linear-example",
      kind: "example",
      title: "An arithmetic pattern is a straight-line rule",
      content: "For 3, 7, 11, 15 the rule is Tn = 4n - 1. Written as f(n) = 4n - 1 the fixed gap of 4 is the gradient, so the thing that made the pattern arithmetic is the thing that makes the function linear.",
      conceptIds: ["concept.sequence-as-function", "concept.arithmetic-sequence"],
      supportedLayers: ["mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.sequence-as-function.half-position-non-example",
      kind: "non-example",
      title: "There is no term two and a half",
      content: "Putting 2.5 into Tn = 4n - 1 returns 9, and the sequence has no such term. The arithmetic works, so nothing complains, and the answer still means nothing: the rule is only asked about whole positions.",
      conceptIds: ["concept.sequence-as-function"],
      supportedLayers: ["mechanics", "exam-patterns"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.sequence-as-function.rewriting-procedure",
      kind: "procedure",
      title: "Turning a pattern into a rule you can question",
      content: "Find Tn for the sequence. Write it as f(n). Anything asked of a function can now be asked of the pattern: which position gives a stated value is f(n) set equal to it, and whether a number appears at all is whether that n is a whole number.",
      conceptIds: ["concept.sequence-as-function"],
      supportedLayers: ["mechanics"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.sequence-as-function.joined-line-misconception",
      kind: "misconception",
      title: "Reading the line drawn through the points",
      content: "A line drawn through plotted terms invites reading values between them. The line is a drawing aid and the sequence is only the dots, which is the same care a graph of a function needs where the domain has gaps in it.",
      conceptIds: ["concept.sequence-as-function"],
      supportedLayers: ["mechanics", "exam-patterns"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.sequence-as-function.delivery-application",
      kind: "application",
      title: "The nth parcel on a round",
      content: "A driver takes 25 minutes to the first drop and 9 minutes between drops after that. Minutes to the nth drop is f(n) = 25 + 9(n - 1), and asking which drop happens by half past three is that rule questioned as a function.",
      conceptIds: ["concept.sequence-as-function"],
      supportedLayers: ["intuition", "exam-patterns"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.sequence-as-function.exam-pattern",
      kind: "exam-pattern",
      title: "Exam pattern: which position holds this value",
      content: "A question gives a general term and a value and asks whether the value is in the sequence. Setting the general term equal to the value and solving for n answers it, and the answer is no whenever n comes out fractional or negative.",
      conceptIds: ["concept.sequence-as-function"],
      supportedLayers: ["exam-patterns"],
      version: "math-lumina.seed.v1",
    }),
    knowledgeAsset({
      id: "asset.sequence-as-function.position-is-input-bridge",
      kind: "representation",
      representationForm: "verbal",
      title: "From a pattern to a function, in one sentence",
      content: "A pattern hands back one term for each position. A function hands back one output for each input. Calling the position an input is the whole of the move, and everything already known about functions arrives with it.",
      conceptIds: ["concept.sequence-as-function", "concept.number-pattern"],
      supportedLayers: ["intuition"],
      version: "math-lumina.seed.v1",
    }),
  ],
  experiences: [
    // -----------------------------------------------------------------------
    // concept.number-pattern
    // -----------------------------------------------------------------------
    learningExperience({
      id: "experience.number-pattern.intuition-what-decides-next",
      title: "What decides the next number",
      intent: "intuition",
      targetConceptIds: ["concept.number-pattern"],
      knowledgeAssetIds: [
        "asset.number-pattern.paving-representation",
        "asset.number-pattern.position-table-representation",
        "asset.number-pattern.next-term-example",
        "asset.number-pattern.savings-application",
      ],
      pedagogicalLayers: ["intuition"],
      deliveryRequirements: ["displayed-text"],
      learnerInteractionRequirements: ["reflection"],
      expectedEvidenceTypes: ["reflection"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.number-pattern.low-energy-core-insight",
      title: "Number pattern core insight",
      intent: "low-energy",
      targetConceptIds: ["concept.number-pattern"],
      knowledgeAssetIds: ["asset.number-pattern.paving-representation"],
      pedagogicalLayers: ["intuition"],
      deliveryRequirements: ["displayed-text"],
      learnerInteractionRequirements: [],
      expectedEvidenceTypes: [],
      completionSemantics: { requiresLearnerInteraction: false, evidenceRequiredForCompletion: false },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.number-pattern.reflection",
      title: "Reflect on what a pattern is claiming",
      intent: "reflection",
      targetConceptIds: ["concept.number-pattern"],
      knowledgeAssetIds: [
        "asset.number-pattern.stated-rule-non-example",
        "asset.number-pattern.three-terms-misconception",
      ],
      pedagogicalLayers: ["intuition", "mechanics", "exam-patterns"],
      deliveryRequirements: ["displayed-text"],
      learnerInteractionRequirements: ["reflection"],
      expectedEvidenceTypes: ["reflection"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.number-pattern.mechanics-gaps",
      title: "Finding a rule by looking at the gaps",
      intent: "mechanics",
      targetConceptIds: ["concept.number-pattern"],
      knowledgeAssetIds: [
        "asset.number-pattern.term-notation-representation",
        "asset.number-pattern.finding-gaps-procedure",
        "asset.number-pattern.position-table-representation",
      ],
      pedagogicalLayers: ["mechanics"],
      deliveryRequirements: ["displayed-text", "displayed-notation"],
      learnerInteractionRequirements: ["reflection"],
      expectedEvidenceTypes: ["reflection"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.number-pattern.practice-next-terms",
      title: "Practise continuing a pattern and saying why",
      intent: "practice",
      targetConceptIds: ["concept.number-pattern"],
      knowledgeAssetIds: [
        "asset.number-pattern.next-term-example",
        "asset.number-pattern.finding-gaps-procedure",
      ],
      pedagogicalLayers: ["mechanics"],
      deliveryRequirements: ["displayed-text", "typed-input"],
      learnerInteractionRequirements: ["practice-input"],
      expectedEvidenceTypes: ["practice-attempt"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.number-pattern.exam-patterns-next-two",
      title: "Exam pattern: the next two terms and the rule",
      intent: "exam-patterns",
      targetConceptIds: ["concept.number-pattern"],
      knowledgeAssetIds: [
        "asset.number-pattern.exam-pattern",
        "asset.number-pattern.savings-application",
      ],
      pedagogicalLayers: ["exam-patterns"],
      deliveryRequirements: ["displayed-text", "typed-input"],
      learnerInteractionRequirements: ["practice-input"],
      expectedEvidenceTypes: ["practice-attempt"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),

    // -----------------------------------------------------------------------
    // concept.arithmetic-sequence
    // -----------------------------------------------------------------------
    learningExperience({
      id: "experience.arithmetic-sequence.intuition-same-amount",
      title: "The same amount added every time",
      intent: "intuition",
      targetConceptIds: ["concept.arithmetic-sequence"],
      knowledgeAssetIds: [
        "asset.arithmetic-sequence.stacked-chairs-representation",
        "asset.arithmetic-sequence.difference-table-representation",
        "asset.arithmetic-sequence.repayment-application",
      ],
      pedagogicalLayers: ["intuition"],
      deliveryRequirements: ["displayed-text"],
      learnerInteractionRequirements: ["reflection"],
      expectedEvidenceTypes: ["reflection"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.arithmetic-sequence.low-energy-core-insight",
      title: "Arithmetic sequence core insight",
      intent: "low-energy",
      targetConceptIds: ["concept.arithmetic-sequence"],
      knowledgeAssetIds: ["asset.arithmetic-sequence.stacked-chairs-representation"],
      pedagogicalLayers: ["intuition"],
      deliveryRequirements: ["displayed-text"],
      learnerInteractionRequirements: [],
      expectedEvidenceTypes: [],
      completionSemantics: { requiresLearnerInteraction: false, evidenceRequiredForCompletion: false },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.arithmetic-sequence.reflection",
      title: "Reflect on why the rule subtracts one",
      intent: "reflection",
      targetConceptIds: ["concept.arithmetic-sequence"],
      knowledgeAssetIds: [
        "asset.arithmetic-sequence.off-by-one-misconception",
        "asset.arithmetic-sequence.doubling-non-example",
      ],
      pedagogicalLayers: ["intuition", "mechanics", "exam-patterns"],
      deliveryRequirements: ["displayed-text"],
      learnerInteractionRequirements: ["reflection"],
      expectedEvidenceTypes: ["reflection"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.arithmetic-sequence.bridge-to-function-view",
      title: "From a pattern to a function, and what comes with it",
      intent: "concept-bridge",
      // Bridged from arithmetic sequences rather than from number patterns,
      // because that is the crossing the graph actually declares. A rule for
      // the nth term is already a rule taking n, so there is something to carry
      // over; from a bare pattern there would not yet be.
      targetConceptIds: ["concept.arithmetic-sequence"],
      knowledgeAssetIds: [
        "asset.sequence-as-function.position-is-input-bridge",
        "asset.sequence-as-function.position-as-input-representation",
        "asset.sequence-as-function.mapping-table-representation",
      ],
      pedagogicalLayers: ["intuition"],
      deliveryRequirements: ["displayed-text"],
      learnerInteractionRequirements: ["reflection"],
      expectedEvidenceTypes: ["reflection"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.arithmetic-sequence.mechanics-general-term",
      title: "Writing the rule for the nth term",
      intent: "mechanics",
      targetConceptIds: ["concept.arithmetic-sequence"],
      knowledgeAssetIds: [
        "asset.arithmetic-sequence.general-term-representation",
        "asset.arithmetic-sequence.finding-rule-procedure",
        "asset.arithmetic-sequence.finding-term-example",
        "asset.arithmetic-sequence.off-by-one-misconception",
      ],
      pedagogicalLayers: ["mechanics"],
      deliveryRequirements: ["displayed-text", "displayed-notation"],
      learnerInteractionRequirements: ["reflection"],
      expectedEvidenceTypes: ["reflection"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.arithmetic-sequence.practice-general-term",
      title: "Practise finding a term far along",
      intent: "practice",
      targetConceptIds: ["concept.arithmetic-sequence"],
      knowledgeAssetIds: [
        "asset.arithmetic-sequence.finding-term-example",
        "asset.arithmetic-sequence.general-term-representation",
      ],
      pedagogicalLayers: ["mechanics"],
      deliveryRequirements: ["displayed-text", "typed-input"],
      learnerInteractionRequirements: ["practice-input"],
      expectedEvidenceTypes: ["practice-attempt"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.arithmetic-sequence.exam-patterns-backwards",
      title: "Exam pattern: which position holds a given term",
      intent: "exam-patterns",
      targetConceptIds: ["concept.arithmetic-sequence"],
      knowledgeAssetIds: [
        "asset.arithmetic-sequence.exam-pattern",
        "asset.arithmetic-sequence.evenly-spaced-representation",
        "asset.arithmetic-sequence.repayment-application",
      ],
      pedagogicalLayers: ["exam-patterns"],
      deliveryRequirements: ["displayed-text", "typed-input"],
      learnerInteractionRequirements: ["practice-input"],
      expectedEvidenceTypes: ["practice-attempt"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),

    // -----------------------------------------------------------------------
    // concept.quadratic-sequence
    // -----------------------------------------------------------------------
    learningExperience({
      id: "experience.quadratic-sequence.intuition-growth-that-grows",
      title: "When the growth itself is growing",
      intent: "intuition",
      targetConceptIds: ["concept.quadratic-sequence"],
      knowledgeAssetIds: [
        "asset.quadratic-sequence.growing-square-representation",
        "asset.quadratic-sequence.second-difference-representation",
        "asset.quadratic-sequence.seating-application",
      ],
      pedagogicalLayers: ["intuition"],
      deliveryRequirements: ["displayed-text"],
      learnerInteractionRequirements: ["reflection"],
      expectedEvidenceTypes: ["reflection"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.quadratic-sequence.low-energy-core-insight",
      title: "Quadratic sequence core insight",
      intent: "low-energy",
      targetConceptIds: ["concept.quadratic-sequence"],
      knowledgeAssetIds: ["asset.quadratic-sequence.growing-square-representation"],
      pedagogicalLayers: ["intuition"],
      deliveryRequirements: ["displayed-text"],
      learnerInteractionRequirements: [],
      expectedEvidenceTypes: [],
      completionSemantics: { requiresLearnerInteraction: false, evidenceRequiredForCompletion: false },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.quadratic-sequence.reflection",
      title: "Reflect on growing gaps against doubling",
      intent: "reflection",
      targetConceptIds: ["concept.quadratic-sequence"],
      knowledgeAssetIds: [
        "asset.quadratic-sequence.doubling-misconception",
        "asset.quadratic-sequence.arithmetic-non-example",
      ],
      pedagogicalLayers: ["intuition", "mechanics", "exam-patterns"],
      deliveryRequirements: ["displayed-text"],
      learnerInteractionRequirements: ["reflection"],
      expectedEvidenceTypes: ["reflection"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.quadratic-sequence.mechanics-second-differences",
      title: "Two rows of differences and the rule they give",
      intent: "mechanics",
      targetConceptIds: ["concept.quadratic-sequence"],
      knowledgeAssetIds: [
        "asset.quadratic-sequence.general-term-representation",
        "asset.quadratic-sequence.building-rule-procedure",
        "asset.quadratic-sequence.finding-rule-example",
        "asset.quadratic-sequence.second-difference-representation",
      ],
      pedagogicalLayers: ["mechanics"],
      deliveryRequirements: ["displayed-text", "displayed-notation"],
      learnerInteractionRequirements: ["reflection"],
      expectedEvidenceTypes: ["reflection"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.quadratic-sequence.practice-second-difference",
      title: "Practise finding the second difference",
      intent: "practice",
      targetConceptIds: ["concept.quadratic-sequence"],
      knowledgeAssetIds: [
        "asset.quadratic-sequence.finding-rule-example",
        "asset.quadratic-sequence.building-rule-procedure",
      ],
      pedagogicalLayers: ["mechanics"],
      deliveryRequirements: ["displayed-text", "typed-input"],
      learnerInteractionRequirements: ["practice-input"],
      expectedEvidenceTypes: ["practice-attempt"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.quadratic-sequence.exam-patterns-general-term",
      title: "Exam pattern: differences first, then the general term",
      intent: "exam-patterns",
      targetConceptIds: ["concept.quadratic-sequence"],
      knowledgeAssetIds: [
        "asset.quadratic-sequence.exam-pattern",
        "asset.quadratic-sequence.curving-points-representation",
        "asset.quadratic-sequence.seating-application",
      ],
      pedagogicalLayers: ["exam-patterns"],
      deliveryRequirements: ["displayed-text", "typed-input"],
      learnerInteractionRequirements: ["practice-input"],
      expectedEvidenceTypes: ["practice-attempt"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),

    // -----------------------------------------------------------------------
    // concept.sequence-as-function
    // -----------------------------------------------------------------------
    learningExperience({
      id: "experience.sequence-as-function.intuition-position-is-input",
      title: "The position is the input",
      intent: "intuition",
      targetConceptIds: ["concept.sequence-as-function"],
      knowledgeAssetIds: [
        "asset.sequence-as-function.position-as-input-representation",
        "asset.sequence-as-function.mapping-table-representation",
        "asset.sequence-as-function.delivery-application",
      ],
      pedagogicalLayers: ["intuition"],
      deliveryRequirements: ["displayed-text"],
      learnerInteractionRequirements: ["reflection"],
      expectedEvidenceTypes: ["reflection"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.sequence-as-function.low-energy-core-insight",
      title: "Pattern and function core insight",
      intent: "low-energy",
      targetConceptIds: ["concept.sequence-as-function"],
      knowledgeAssetIds: ["asset.sequence-as-function.position-is-input-bridge"],
      pedagogicalLayers: ["intuition"],
      deliveryRequirements: ["displayed-text"],
      learnerInteractionRequirements: [],
      expectedEvidenceTypes: [],
      completionSemantics: { requiresLearnerInteraction: false, evidenceRequiredForCompletion: false },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.sequence-as-function.reflection",
      title: "Reflect on the line that is not there",
      intent: "reflection",
      targetConceptIds: ["concept.sequence-as-function"],
      knowledgeAssetIds: [
        "asset.sequence-as-function.joined-line-misconception",
        "asset.sequence-as-function.half-position-non-example",
        "asset.sequence-as-function.separated-points-representation",
      ],
      pedagogicalLayers: ["intuition", "mechanics", "exam-patterns"],
      deliveryRequirements: ["displayed-text"],
      learnerInteractionRequirements: ["reflection"],
      expectedEvidenceTypes: ["reflection"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.sequence-as-function.mechanics-rewriting",
      title: "Writing Tn as f(n) and asking function questions of it",
      intent: "mechanics",
      targetConceptIds: ["concept.sequence-as-function"],
      knowledgeAssetIds: [
        "asset.sequence-as-function.notation-representation",
        "asset.sequence-as-function.rewriting-procedure",
        "asset.sequence-as-function.arithmetic-is-linear-example",
      ],
      pedagogicalLayers: ["mechanics"],
      deliveryRequirements: ["displayed-text", "displayed-notation"],
      learnerInteractionRequirements: ["reflection"],
      expectedEvidenceTypes: ["reflection"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.sequence-as-function.practice-is-it-a-term",
      title: "Practise deciding whether a number is in the sequence",
      intent: "practice",
      targetConceptIds: ["concept.sequence-as-function"],
      knowledgeAssetIds: [
        "asset.sequence-as-function.rewriting-procedure",
        "asset.sequence-as-function.half-position-non-example",
      ],
      pedagogicalLayers: ["mechanics"],
      deliveryRequirements: ["displayed-text", "typed-input"],
      learnerInteractionRequirements: ["practice-input"],
      expectedEvidenceTypes: ["practice-attempt"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
    learningExperience({
      id: "experience.sequence-as-function.exam-patterns-which-position",
      title: "Exam pattern: solve for the position",
      intent: "exam-patterns",
      targetConceptIds: ["concept.sequence-as-function"],
      knowledgeAssetIds: [
        "asset.sequence-as-function.exam-pattern",
        "asset.sequence-as-function.separated-points-representation",
        // The habit of joining the dots and reading between them is an exam
        // habit, so the misconception is offered where it bites and not only
        // in reflection.
        "asset.sequence-as-function.joined-line-misconception",
        "asset.sequence-as-function.delivery-application",
      ],
      pedagogicalLayers: ["exam-patterns"],
      deliveryRequirements: ["displayed-text", "typed-input"],
      learnerInteractionRequirements: ["practice-input"],
      expectedEvidenceTypes: ["practice-attempt"],
      completionSemantics: { requiresLearnerInteraction: true, evidenceRequiredForCompletion: true },
      version: "math-lumina.seed.v1",
    }),
  ],
};
